version: "3.10"

services:
  web:
    image: gcr.io/${GCP_PJ_ID}/${IMAGE_NAME}:latest
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
